import 'server-only';
import PDFDocument from 'pdfkit';
import { num, money } from './money';
import { fmtDate, fmtDateTime, isoDate } from './dates';
import type { OrganisationSettings } from './settings';

export const NAVY = '#0e2340';
export const GOLD = '#b8860b';
export const GREY = '#5b6472';
export const LIGHT = '#f4f6f9';

export interface PdfColumn {
  key: string;
  label: string;
  width?: number; // points; remaining space is distributed automatically
  align?: 'left' | 'right' | 'center';
  format?: (value: any, row: any) => string;
}

export interface PdfTableOptions {
  columns: PdfColumn[];
  rows: any[];
  startY?: number;
  rowHeight?: number;
  fontSize?: number;
  totals?: Record<string, any>;
  emptyText?: string;
}

export interface PdfMeta {
  org: OrganisationSettings;
  title: string;
  subtitle?: string;
  filters?: string[];
  footer?: string;
  showPageNumbers?: boolean;
}

/* ------------------------------------------------------------------ *
 * Document scaffolding
 * ------------------------------------------------------------------ */
export function createPdf(meta: PdfMeta): PDFKit.PDFDocument {
  // `bufferPages` keeps every page in memory so footers and "Page x of y"
  // numbers can be drawn once the document is complete (pdfkit >= 0.15 option).
  const doc = new PDFDocument({
    size: 'A4',
    margin: 40,
    bufferPages: true,
    info: { Title: meta.title, Author: meta.org.name },
  } as any);

  const drawHeader = () => {
    doc.rect(0, 0, doc.page.width, 74).fill(NAVY);
    doc.rect(0, 74, doc.page.width, 3).fill(GOLD);
    doc.fillColor('#ffffff').fontSize(15).font('Helvetica-Bold')
      .text(meta.org.name, 40, 20, { width: doc.page.width - 80 });
    doc.fontSize(9).font('Helvetica')
      .text(`${meta.org.parish || ''}${meta.org.diocese ? ' · ' + meta.org.diocese : ''}`, 40, 40, {
        width: doc.page.width - 80,
      });
    if (meta.org.motto) {
      doc.fillColor('#e7c86a').fontSize(8).font('Helvetica-Oblique')
        .text(meta.org.motto, 40, 54, { width: doc.page.width - 80 });
    }
    doc.fillColor('#000000');
    doc.y = 96;
    doc.x = 40;
  };

  drawHeader();

  doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(15).text(meta.title, 40, doc.y, { align: 'center' });
  doc.moveDown(0.2);
  if (meta.subtitle) {
    doc.fillColor(GREY).font('Helvetica').fontSize(9.5).text(meta.subtitle, 40, doc.y, { align: 'center' });
    doc.moveDown(0.2);
  }
  if (meta.filters?.length) {
    doc.fillColor(GREY).fontSize(8.5).text(meta.filters.join('   |   '), 40, doc.y, { align: 'center' });
    doc.moveDown(0.4);
  }
  doc.moveDown(0.4);

  const footerText =
    meta.footer ||
    `Generated by the ${meta.org.name} management system on ${fmtDateTime(new Date())}`;

  doc.on('pageAdded', () => {
    drawHeader();
    doc.moveDown(0.4);
  });

  // Footer is drawn when the stream is finalised (see finishPdf) so that page
  // numbers can include the total count.
  (doc as any).__meta = meta;
  (doc as any).__footerText = footerText;

  return doc;
}

export function finishPdf(doc: PDFKit.PDFDocument): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const chunks: Buffer[] = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const meta: PdfMeta = (doc as any).__meta;
    const footerText: string = (doc as any).__footerText;
    const pages: any = (doc as any)._pageBuffer || [];
    const range = doc.bufferedPageRange();
    for (let i = range.start; i < range.start + range.count; i++) {
      doc.switchToPage(i);
      const bottom = doc.page.height - 34;
      doc.save();
      doc.rect(0, bottom - 6, doc.page.width, 40).fill(LIGHT);
      doc.fillColor(GREY).font('Helvetica').fontSize(7.5)
        .text(footerText, 40, bottom + 2, { width: doc.page.width - 160, align: 'left' });
      if (meta?.showPageNumbers !== false) {
        doc.text(`Page ${i + 1} of ${range.count}`, doc.page.width - 140, bottom + 2, {
          width: 100,
          align: 'right',
        });
      }
      doc.restore();
    }
    doc.end();
    void pages;
  });
}

export async function renderPdf(meta: PdfMeta, draw: (doc: PDFKit.PDFDocument) => void | Promise<void>): Promise<Buffer> {
  const doc = createPdf({ ...meta, showPageNumbers: true });
  await draw(doc);
  return finishPdf(doc);
}

/* ------------------------------------------------------------------ *
 * Reusable primitives
 * ------------------------------------------------------------------ */
export function sectionTitle(doc: PDFKit.PDFDocument, text: string) {
  doc.moveDown(0.6);
  const y = doc.y;
  doc.rect(40, y, doc.page.width - 80, 18).fill(NAVY);
  doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(10).text(text.toUpperCase(), 46, y + 4.5, {
    width: doc.page.width - 92,
  });
  doc.fillColor('#000000').font('Helvetica');
  doc.y = y + 24;
  doc.x = 40;
}

export function keyValueGrid(doc: PDFKit.PDFDocument, entries: [string, string | number | null | undefined][], columns = 2) {
  const width = (doc.page.width - 80) / columns;
  const rows = Math.ceil(entries.length / columns);
  const rowHeight = 26;
  if (doc.y + rows * rowHeight > doc.page.height - 70) doc.addPage();
  const startY = doc.y;

  entries.forEach(([label, value], i) => {
    const col = i % columns;
    const row = Math.floor(i / columns);
    const x = 40 + col * width;
    const y = startY + row * rowHeight;
    doc.fillColor(GREY).font('Helvetica').fontSize(7.5).text(String(label).toUpperCase(), x, y, { width: width - 10 });
    doc.fillColor('#111827').font('Helvetica-Bold').fontSize(9)
      .text(value === null || value === undefined || value === '' ? '—' : String(value), x, y + 9, { width: width - 10 });
  });

  doc.fillColor('#000000').font('Helvetica');
  doc.y = startY + rows * rowHeight + 4;
  doc.x = 40;
}

export function drawTable(doc: PDFKit.PDFDocument, opts: PdfTableOptions) {
  const { columns, rows } = opts;
  const fontSize = opts.fontSize ?? 8.5;
  const rowHeight = opts.rowHeight ?? 17;
  const tableWidth = doc.page.width - 80;
  const fixed = columns.reduce((a, c) => a + (c.width || 0), 0);
  const flexCount = columns.filter((c) => !c.width).length || 1;
  const flexWidth = Math.max(40, (tableWidth - fixed) / flexCount);
  const widths = columns.map((c) => c.width || flexWidth);

  const drawHeaderRow = (y: number) => {
    doc.rect(40, y, tableWidth, rowHeight).fill(NAVY);
    let x = 40;
    columns.forEach((c, i) => {
      doc.fillColor('#ffffff').font('Helvetica-Bold').fontSize(fontSize - 0.5)
        .text(c.label, x + 4, y + 4.5, { width: widths[i] - 8, align: c.align === 'right' ? 'right' : c.align === 'center' ? 'center' : 'left', ellipsis: true, height: rowHeight });
      x += widths[i];
    });
    doc.fillColor('#000000').font('Helvetica');
    return y + rowHeight;
  };

  let y = opts.startY ?? doc.y;
  y = drawHeaderRow(y);

  if (!rows.length) {
    doc.rect(40, y, tableWidth, 26).fill(LIGHT);
    doc.fillColor(GREY).fontSize(fontSize).text(opts.emptyText || 'No records found.', 40, y + 8, {
      width: tableWidth,
      align: 'center',
    });
    doc.fillColor('#000000');
    doc.y = y + 32;
    return;
  }

  rows.forEach((row, index) => {
    if (y + rowHeight > doc.page.height - 60) {
      doc.addPage();
      y = drawHeaderRow(doc.y);
    }
    if (index % 2 === 1) doc.rect(40, y, tableWidth, rowHeight).fill('#f7f9fc');
    let x = 40;
    columns.forEach((c, i) => {
      const raw = row[c.key];
      const text = c.format ? c.format(raw, row) : raw === null || raw === undefined ? '—' : String(raw);
      doc.fillColor('#111827').font('Helvetica').fontSize(fontSize)
        .text(text, x + 4, y + 4.5, {
          width: widths[i] - 8,
          align: c.align === 'right' ? 'right' : c.align === 'center' ? 'center' : 'left',
          ellipsis: true,
          height: rowHeight,
        });
      x += widths[i];
    });
    doc.moveTo(40, y + rowHeight).lineTo(40 + tableWidth, y + rowHeight).strokeColor('#e5e9f0').lineWidth(0.5).stroke();
    y += rowHeight;
  });

  if (opts.totals) {
    if (y + rowHeight > doc.page.height - 60) {
      doc.addPage();
      y = doc.y;
    }
    doc.rect(40, y, tableWidth, rowHeight).fill('#eef2f8');
    let x = 40;
    columns.forEach((c, i) => {
      const value = opts.totals![c.key];
      if (value !== undefined && value !== null) {
        doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(fontSize)
          .text(String(value), x + 4, y + 4.5, { width: widths[i] - 8, align: c.align === 'right' ? 'right' : 'left' });
      }
      x += widths[i];
    });
    y += rowHeight;
  }

  doc.y = y + 8;
  doc.x = 40;
  doc.fillColor('#000000').font('Helvetica');
}

export function statBoxes(doc: PDFKit.PDFDocument, stats: [string, string][]) {
  if (!stats.length) return;
  const boxWidth = (doc.page.width - 80 - (stats.length - 1) * 8) / stats.length;
  const height = 44;
  if (doc.y + height > doc.page.height - 60) doc.addPage();
  const y = doc.y;
  stats.forEach(([label, value], i) => {
    const x = 40 + i * (boxWidth + 8);
    doc.roundedRect(x, y, boxWidth, height, 4).fillAndStroke(LIGHT, '#dfe5ee');
    doc.fillColor(GREY).font('Helvetica').fontSize(7.5).text(label.toUpperCase(), x + 6, y + 7, { width: boxWidth - 12 });
    doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(12).text(value, x + 6, y + 22, { width: boxWidth - 12 });
  });
  doc.fillColor('#000000').font('Helvetica');
  doc.y = y + height + 12;
  doc.x = 40;
}

/* ------------------------------------------------------------------ *
 * RECEIPT PDF
 * ------------------------------------------------------------------ */
export async function receiptPdf(input: {
  org: OrganisationSettings;
  receipt: any;
  member: any;
  allocations?: any[];
  parishName?: string;
}): Promise<Buffer> {
  const { org, receipt, member, allocations = [] } = input;
  return renderPdf({ org, title: 'OFFICIAL RECEIPT', subtitle: receipt.receipt_no }, (doc) => {
    const width = doc.page.width - 80;
    const top = doc.y;
    doc.roundedRect(40, top, width, 62, 6).fillAndStroke('#ffffff', GOLD).lineWidth(1.5);
    doc.fillColor(GREY).font('Helvetica').fontSize(8).text('RECEIPT NUMBER', 54, top + 10);
    doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(14).text(String(receipt.receipt_no), 54, top + 21);
    doc.fillColor(GREY).font('Helvetica').fontSize(8.5).text(`Issued ${fmtDateTime(receipt.issued_at)}`, 54, top + 42);
    doc.fillColor(GREY).font('Helvetica').fontSize(8).text('AMOUNT RECEIVED', 40 + width - 200, top + 10, { width: 186, align: 'right' });
    doc.fillColor(GOLD).font('Helvetica-Bold').fontSize(20).text(money(receipt.amount), 40 + width - 200, top + 20, {
      width: 186,
      align: 'right',
    });
    doc.fillColor(receipt.status === 'valid' ? '#15803d' : '#b91c1c').font('Helvetica-Bold').fontSize(8.5)
      .text(String(receipt.status || 'valid').toUpperCase(), 40 + width - 200, top + 46, { width: 186, align: 'right' });
    doc.fillColor('#000000').font('Helvetica');
    doc.y = top + 78;
    doc.x = 40;

    keyValueGrid(doc, [
      ['Received from', member?.full_name],
      ['CMA number', member?.membership_no],
      ['Phone', member?.phone],
      ['Parish / Church', receipt.parish_name || org.parish],
      ['Payment method', receipt.payment_method],
      ['Reference', receipt.reference || '—'],
      ['Category', receipt.category],
      ['Status', (receipt.status || 'valid').toUpperCase()],
    ]);

    doc.moveDown(0.4);
    sectionTitle(doc, 'Payment details');
    drawTable(doc, {
      columns: [
        { key: 'description', label: 'Description' },
        { key: 'period', label: 'Period', width: 70, align: 'center' },
        { key: 'amount', label: 'Amount (KSh)', width: 100, align: 'right', format: (v: any) => money(v, { symbol: false }) },
      ],
      rows: allocations.length
        ? allocations.map((a) => ({
            description: a.label || a.allocation_type,
            period: a.period || '—',
            amount: a.amount,
          }))
        : [{ description: receipt.description || receipt.category, period: '—', amount: receipt.amount }],
      totals: { description: 'TOTAL PAID', amount: money(receipt.amount, { symbol: false }) },
    });

    if (receipt.balance_after !== null && receipt.balance_after !== undefined) {
      doc.moveDown(0.3);
      doc.fillColor(GREY).fontSize(9)
        .text(`Outstanding balance after this payment: ${money(receipt.balance_after)}`, 40, doc.y, { width });
      doc.fillColor('#000000');
    }

    doc.moveDown(2.6);
    const signatureY = doc.y;
    doc.moveTo(40, signatureY + 30).lineTo(220, signatureY + 30).strokeColor('#94a3b8').lineWidth(0.8).stroke();
    doc.fillColor(GREY).fontSize(8).text('Authorised signature / stamp', 40, signatureY + 34, { width: 180 });
    doc.fontSize(8).text('This is a computer-generated receipt and is valid without a seal.', 40, signatureY + 60, {
      width,
    });
    doc.fillColor('#000000');
  });
}

/* ------------------------------------------------------------------ *
 * MEMBER STATEMENT PDF
 * ------------------------------------------------------------------ */
export async function statementPdf(input: {
  org: OrganisationSettings;
  statement: Awaited<ReturnType<typeof import('./payments').memberStatement>>;
}): Promise<Buffer> {
  const { org, statement } = input;
  const m = statement.member;
  const b = statement.balances;

  return renderPdf(
    {
      org,
      title: 'CONSOLIDATED MEMBER STATEMENT',
      subtitle: `${m.full_name} · CMA No. ${m.membership_no}`,
      filters: [
        statement.range.from ? `From ${fmtDate(statement.range.from)}` : 'From inception',
        statement.range.to ? `To ${fmtDate(statement.range.to)}` : `To ${fmtDate(new Date())}`,
        `Generated ${fmtDateTime(new Date())}`,
      ],
    },
    (doc) => {
      keyValueGrid(doc, [
        ['Member', m.full_name],
        ['CMA number', m.membership_no],
        ['Phone', m.phone],
        ['Email', m.email || '—'],
        ['Parish', m.parish_name],
        ['Church / Outstation', m.church_name || '—'],
        ['Small Christian Community', m.scc_name || '—'],
        ['Membership status', String(m.membership_status).toUpperCase()],
        ['Date joined', fmtDate(m.date_joined)],
        ['SDP / Sacco account', b.account_no || '—'],
      ]);

      statBoxes(doc, [
        ['Savings balance', money(b.savings_balance)],
        ['Shares', `${b.shares_count} (${money(b.shares_value)})`],
        ['Loan balance', money(b.loan_outstanding)],
        ['Arrears', money(b.loan_arrears)],
        ['Outstanding', money(b.total_outstanding)],
      ]);

      const columnsFor = (hasBalance = false): PdfColumn[] => {
        const cols: PdfColumn[] = [
          { key: 'date', label: 'Date', width: 66, format: (v: any) => fmtDate(v, 'dd/MM/yyyy') },
          { key: 'description', label: 'Description' },
          { key: 'reference', label: 'Reference', width: 92 },
          { key: 'debit', label: 'Due / Debit', width: 78, align: 'right', format: (v: any) => (num(v) ? money(v, { symbol: false }) : '—') },
          { key: 'credit', label: 'Paid / Credit', width: 78, align: 'right', format: (v: any) => (num(v) ? money(v, { symbol: false }) : '—') },
        ];
        if (hasBalance)
          cols.push({ key: 'balance', label: 'Balance', width: 78, align: 'right', format: (v: any) => money(v, { symbol: false }) });
        return cols;
      };

      for (const section of statement.sections) {
        sectionTitle(doc, `${section.title}  —  KSh ${num(section.total_credit).toLocaleString()}`);
        drawTable(doc, {
          columns: columnsFor(section.key === 'savings' || section.key === 'loan_repayments' || section.key === 'loans'),
          rows: section.rows,
          emptyText: `No ${section.title.toLowerCase()} recorded in this period.`,
          totals: section.rows.length
            ? {
                description: 'Section total',
                debit: num(section.total_debit) ? money(section.total_debit, { symbol: false }) : '—',
                credit: num(section.total_credit) ? money(section.total_credit, { symbol: false }) : '—',
              }
            : undefined,
        });
      }

      sectionTitle(doc, 'OUTSTANDING BALANCES');
      drawTable(doc, {
        columns: [
          { key: 'item', label: 'Item' },
          { key: 'amount', label: 'Amount (KSh)', width: 120, align: 'right', format: (v: any) => money(v, { symbol: false }) },
        ],
        rows: [
          { item: 'Unpaid monthly CMA contributions', amount: b.monthly_outstanding },
          { item: 'Contribution penalties', amount: b.contribution_penalties },
          { item: 'Other penalties & fees', amount: b.penalties_outstanding },
          { item: 'Outstanding loan balance', amount: b.loan_outstanding },
          { item: 'Loan arrears (overdue instalments)', amount: b.loan_arrears },
        ],
        totals: { item: 'TOTAL OUTSTANDING', amount: money(b.total_outstanding, { symbol: false }) },
      });

      sectionTitle(doc, 'DECLARATION');
      doc.fontSize(8.5).fillColor('#334155')
        .text(
          `This statement was produced electronically by the ${org.name} management system and reflects all contributions, welfare, funeral, wedding, project, SDP/Sacco savings, shares, loans and repayments recorded against CMA number ${m.membership_no} for the period shown. Amounts are in Kenya Shillings. Should any entry be disputed, please contact the CMA Treasurer or Secretary within 30 days.`,
          40,
          doc.y,
          { width: doc.page.width - 80, align: 'justify' },
        );
      doc.fillColor('#000000');
    },
  );
}

/* ------------------------------------------------------------------ *
 * GENERIC REPORT PDF
 * ------------------------------------------------------------------ */
export async function reportPdf(input: {
  org: OrganisationSettings;
  title: string;
  subtitle?: string;
  filters?: string[];
  stats?: [string, string][];
  sections: { title?: string; columns: PdfColumn[]; rows: any[]; totals?: Record<string, any>; emptyText?: string }[];
  notes?: string;
}): Promise<Buffer> {
  return renderPdf({ org: input.org, title: input.title, subtitle: input.subtitle, filters: input.filters }, (doc) => {
    if (input.stats?.length) statBoxes(doc, input.stats);
    for (const section of input.sections) {
      if (section.title) sectionTitle(doc, section.title);
      drawTable(doc, {
        columns: section.columns,
        rows: section.rows,
        totals: section.totals,
        emptyText: section.emptyText,
      });
    }
    if (input.notes) {
      doc.moveDown(0.6);
      doc.fillColor(GREY).fontSize(8).text(input.notes, 40, doc.y, { width: doc.page.width - 80 });
      doc.fillColor('#000000');
    }
  });
}

/* ------------------------------------------------------------------ *
 * SHARE CERTIFICATE
 * ------------------------------------------------------------------ */
export async function shareCertificatePdf(input: {
  org: OrganisationSettings;
  member: any;
  share: any;
  totalShares: number;
}): Promise<Buffer> {
  const { org, member, share, totalShares } = input;
  return renderPdf({ org, title: 'SHARE CERTIFICATE', subtitle: share.certificate_no }, (doc) => {
    const width = doc.page.width - 80;
    doc.roundedRect(40, doc.y, width, 210, 8).lineWidth(2).stroke(GOLD);
    doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(11)
      .text(org.name.toUpperCase(), 40, doc.y + 22, { width, align: 'center' });
    doc.fillColor(GREY).font('Helvetica').fontSize(9)
      .text(`${org.parish || ''}${org.diocese ? ' · ' + org.diocese : ''}`, 40, doc.y + 6, { width, align: 'center' });
    doc.fillColor(GOLD).font('Helvetica-Bold').fontSize(18)
      .text('SDP / SACCO SHARE CERTIFICATE', 40, doc.y + 22, { width, align: 'center' });
    doc.fillColor('#111827').font('Helvetica').fontSize(10)
      .text('This is to certify that', 40, doc.y + 18, { width, align: 'center' });
    doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(15)
      .text(member.full_name, 40, doc.y + 6, { width, align: 'center' });
    doc.fillColor('#111827').font('Helvetica').fontSize(10)
      .text(`CMA Membership No. ${member.membership_no}`, 40, doc.y + 6, { width, align: 'center' });
    doc.font('Helvetica-Bold').fontSize(12)
      .text(`is the registered holder of ${num(share.shares_count)} share(s) of KSh ${num(share.value_per_share).toLocaleString()} each`, 40, doc.y + 14, {
        width,
        align: 'center',
      });
    doc.font('Helvetica').fontSize(10)
      .text(`Total value: ${money(num(share.shares_count) * num(share.value_per_share))}   ·   Total shares held: ${totalShares}`, 40, doc.y + 6, {
        width,
        align: 'center',
      });
    doc.fillColor(GREY).fontSize(9)
      .text(`Certificate ${share.certificate_no} issued on ${fmtDate(share.issued_date)}`, 40, doc.y + 14, { width, align: 'center' });

    const sigY = doc.y + 26;
    doc.moveTo(70, sigY).lineTo(230, sigY).strokeColor('#94a3b8').stroke();
    doc.moveTo(width - 130, sigY).lineTo(width + 30, sigY).strokeColor('#94a3b8').stroke();
    doc.fillColor(GREY).fontSize(8).text('Chairman', 70, sigY + 4, { width: 160, align: 'center' });
    doc.text('Treasurer / Sacco Officer', width - 130, sigY + 4, { width: 160, align: 'center' });
    doc.fillColor('#000000');
    doc.y = sigY + 40;
  });
}

export async function loanSchedulePdf(input: {
  org: OrganisationSettings;
  member: any;
  loan: any;
  schedule: any[];
}): Promise<Buffer> {
  const { org, member, loan, schedule } = input;
  return renderPdf(
    {
      org,
      title: `LOAN STATEMENT & AMORTISATION SCHEDULE — ${loan.loan_no}`,
      subtitle: `${member.full_name} · CMA No. ${member.membership_no}`,
      filters: [`Disbursed ${fmtDate(loan.disbursed_at)}`, `Maturity ${fmtDate(loan.maturity_date)}`, `Generated ${fmtDate(new Date())}`],
    },
    (doc) => {
      statBoxes(doc, [
        ['Principal', money(loan.principal)],
        ['Interest', money(loan.total_interest)],
        ['Total repayable', money(loan.total_repayable)],
        ['Paid', money(loan.amount_paid)],
        ['Outstanding', money(loan.outstanding_balance)],
      ]);
      drawTable(doc, {
        columns: [
          { key: 'installment_no', label: '#', width: 26, align: 'center' },
          { key: 'due_date', label: 'Due date', width: 70, format: (v: any) => fmtDate(v, 'dd/MM/yyyy') },
          { key: 'opening_balance', label: 'Opening', width: 74, align: 'right', format: (v: any) => money(v, { symbol: false }) },
          { key: 'principal', label: 'Principal', width: 70, align: 'right', format: (v: any) => money(v, { symbol: false }) },
          { key: 'interest', label: 'Interest', width: 64, align: 'right', format: (v: any) => money(v, { symbol: false }) },
          { key: 'total_due', label: 'Instalment', width: 74, align: 'right', format: (v: any) => money(v, { symbol: false }) },
          { key: 'amount_paid', label: 'Paid', width: 70, align: 'right', format: (v: any) => money(v, { symbol: false }) },
          { key: 'balance_after', label: 'Balance', width: 74, align: 'right', format: (v: any) => money(v, { symbol: false }) },
          { key: 'status', label: 'Status', width: 58, align: 'center', format: (v: any) => String(v).toUpperCase() },
        ],
        rows: schedule,
        totals: {
          due_date: 'TOTALS',
          principal: money(schedule.reduce((a, r) => a + num(r.principal), 0), { symbol: false }),
          interest: money(schedule.reduce((a, r) => a + num(r.interest), 0), { symbol: false }),
          total_due: money(schedule.reduce((a, r) => a + num(r.total_due), 0), { symbol: false }),
          amount_paid: money(schedule.reduce((a, r) => a + num(r.amount_paid), 0), { symbol: false }),
        },
      });
    },
  );
}

export { isoDate };
